language: node_js

env: 
  global: 
    secure: "GAng/8E7rAHXGAHwoKkVQlC2w5KF4w41RzrD2nNOKAtqdwTAL/74ZlOBWDeyp198NLGI3zoh8BRL1DEpFlL8gZMHNkh7uHNQVXCTo8gB4nST92pigAi49GKhtwA/pPWT9fma+aUrPiqIvjgELJdJe6O8/WAnxgzP6PzYbiGw2/k="

after_success:
  - git clone -b gh-pages https://github.com/simoneb/jasmine-they.git gh-pages
  - rm -rf gh-pages/*
  - docco -o gh-pages examples/* *.js
  - cd gh-pages
  - cp jasmine-they-examples-spec.html index.html
  - git add -A
  - git config --global user.email "simone.busoli@gmail.com"
  - git config --global user.name "Travis-CI"
  - git config push.default simple
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - git commit -m "Travis build ${TRAVIS_BUILD_NUMBER} pushed to gh-pages"
  - git push
  - rm .git/credentials